### DISCUSSION TITLE
Stripping @labels in karma.conf

### DISCUSSION THREAD

**Discussion by xkilian** [prymitive/karma#3932] [Q&A]
Trying to strip `@cluster` LABEL  for alerts displayed in Karma. @cluster labels always show up in the list of LABELS. Running 0.95 or 0.76, same thing.

- Changing the colour of the cluster LABEL works, 
- Adding an alert filter with `@cluster or @state` works.
- **Strip LABEL `@cluster` does not work**

I am not sure what I am doing wrong here.

```
filters:
  default:
    - "@state=active"
labels:
  color:
    custom:
      "@cluster":
        - value: ALERTMANAGER1
          color: "#ff220c"
  strip:
    - vcenter
    - datastore
    - "@cluster"

```
