### DISCUSSION TITLE
Docker: Include user/password authentication in docker-compose.yml

### DISCUSSION THREAD

**Discussion by cmonty14** [prymitive/karma#5963] [General]
Hi,
I have deployed karma using this docker-compose.yml:
```
services:
  karma:
    environment:
      - ALERTMANAGER_URI=http://prometheus.example.com:9093
    image: ghcr.io/prymitive/karma:latest
    ports:
      - 8080:8080
```
Can you please advise how to modify this compose file in order to add user/password authentication?

In normal setup I would use this config-file _karma.yml_:
```
authentication:
  basicAuth:
    users:
      - username: user
        password: karma
```
