### DISCUSSION TITLE
My endpoints are always proxied

### DISCUSSION THREAD

**Discussion by fr6nco** [prymitive/karma#6415] [Q&A]
Hi,

My requests are always proxied via karma, even if I explicitly set proxy to false.

Here is my config:
```    
   alertmanager:
      servers:
        - name: karma
          uri: https://valid-karma-endpoint.com/
          external_uri: https://valid-karma-endpoint.com/
          proxy: false
          timeout: 5s
```

Trie several combinations of proxy true false, setting external_uri, not setting it. But somehow my requests are always proxied via the karma endpoint. I can see those in chrome webconsole:

```
curl 'https://valid-karma-endpoint.com/history.json' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9,sk;q=0.8,de-DE;q=0.7,de;q=0.6,hu;q=0.5' \
  -H 'content-type: text/plain;charset=UTF-8' \
  -H 'priority: u=1, i' \
  -H 'referer: https://karma.mic-azure-madme-prod.mad-me.com/?q=' \
  -H 'sec-ch-ua: "Chromium";v="134", "Not:A-Brand";v="24", "Google Chrome";v="134"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36' \
  --data-raw '{"sources":["http://---/"],"labels":{"cluster":"---","namespace":"loki","alertname":"KubePersistentVolumeFillingUp","endpoint":"https-metrics","instance":"172.19.55.112:10250","job":"kubelet","metrics_path":"/metrics","node":"aks-madmelegacy-29590177-vmss00000r","persistentvolumeclaim":"storage-loki-0","prometheus":"monitoring/prometheus-stack-kube-prom-prometheus","service":"prometheus-stack-kube-prom-kubelet"}}'
  ```
  
  Since some of those endpoints are not accessible via the karma backend, but should be accessible from my browser since my laptop is joined to the VPN, thus some of those requests get timed out.
  
  Im running ghcr.io/prymitive/karma:v0.121
