### ISSUE TITLE
Feature request: allow custom colorTitlebar based on severity

### ISSUE THREAD

**Issue by jgracenin** [prymitive/karma#1344]
Hello,

Thanks for the awesome project -- we use it everyday to help us monitor our network.

We have this running on a large TV and we want an easy way to identify critical alerts from far away. The colorTitlebar feature is nice, but is limited to red (non-silenced) or green (silenced).

It would be great if I could pass in a custom mapping of severity to color for the titlebar (similar to how the label color config is done). When using this feature, you could force the alert count to have a black background with white text.

The yaml could maybe look something like this (just a sketch, feel free to change):
```
titlebar:
  color:
    silenced: "#18bc9c"
    custom:
      severity:
        - value: info
          color: "#87c4e0"
        - value: warning
          color: "#ffae42"
        - value: critical
          color: "#ff220c"
```

Thanks
