### ISSUE TITLE
external_uri is not used in proxy mode

### ISSUE THREAD

**Issue by Leutin** [prymitive/karma#1430]
Karma v0.55 running in Docker-compose and exposed with nginx as http://10.0.1.1/karma
```
alertmanager:
  servers:
    - name: local
      uri: http://alertmanager:9093
      proxy: true
      external_uri: http://10.0.1.1/alertmanager/
      readonly: false
```
Browser show existing alerts and silences as well, but when I try to edit existing silence with Karma, browser ignores external_uri variable and tries to POST to http://10.0.1.1/proxy/alertmanager/local/api/v2/silences
