### ISSUE TITLE
[Error] TypeError: null is not an object (evaluating 'o.settings.values.staticColorLabels.includes')

### ISSUE THREAD

**Issue by rmartinsjr** [prymitive/karma#1439]
Hi,

After updating my AlertManager docker image to 0.20.0 (build date 20191211-14:13:14) and Karma docker image to karma:latest (v0.55-84-ge91160b), everything looked fine until the first alert arrives. Whenever an alert is shown in Karma, I get an "Internal Error" message on the page and a short description: "null is not an object (evaluating 'o.settings.values.staticColorLabels.includes')".

Karma is very useful, could you please help with this issue?

Here is a snippet from docker-compose file:

```
  alertmanager:
    image: prom/alertmanager
    entrypoint:
      - "/bin/alertmanager"
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
      - "--web.external-url=https://alertmanager.example.com/"
      - "--web.route-prefix=/"
    ports:
      - 9093:9093
    volumes:
      - /opt/alertmanager/etc:/etc/alertmanager
    networks:
      - prometheus
    restart: unless-stopped

  karma:
    image: lmierzwa/karma:latest
    environment:
      - "ALERTMANAGER_URI=http://alertmanager:9093"
    ports:
      - 8080:8080
    networks:
      - prometheus
    restart: unless-stopped
```

And here is Safari's console (a similar message is also display in Chrome):
```
fu - react-dom.production.min.js:196:201

[Error] TypeError: null is not an object (evaluating 'o.settings.values.staticColorLabels.includes')
value — index.js:43
value — index.js:15
value
bt — mobx.module.js:978
(anonymous function) — 6.d292286f.chunk.js:2:202486
at — mobx.module.js:761
(anonymous function) — mobx.module.js:1795
l — 6.d292286f.chunk.js:2:202456
Ka — react-dom.production.min.js:181:192
vs — react-dom.production.min.js:230
ds — react-dom.production.min.js:229:365
is — react-dom.production.min.js:223:216
is
(anonymous function) — react-dom.production.min.js:121:115
(anonymous function) — scheduler.production.min.js:18:437
Ko — react-dom.production.min.js:121
$o — react-dom.production.min.js:120:496
as — react-dom.production.min.js:224:156
Yt — mobx.module.js:1881
Nt — mobx.module.js:1581
(anonymous function) — mobx.module.js:967
gt — mobx.module.js:921
promiseReactionJob

	fu (6.d292286f.chunk.js:2:441123)
	(anonymous function) (6.d292286f.chunk.js:2:447222)
	_i (6.d292286f.chunk.js:2:413793)
	bi (6.d292286f.chunk.js:2:413579)
	bs (6.d292286f.chunk.js:2:465109)
	bs
	(anonymous function) (6.d292286f.chunk.js:2:484514)
	gs (6.d292286f.chunk.js:2:461256)
	is (6.d292286f.chunk.js:2:451583)
	is
	(anonymous function) (6.d292286f.chunk.js:2:409566)
	(anonymous function) (6.d292286f.chunk.js:2:484514)
	Ko (6.d292286f.chunk.js:2:409512)
	$o (6.d292286f.chunk.js:2:409447)
	as (6.d292286f.chunk.js:2:451676)
	Yt (6.d292286f.chunk.js:2:21509)
	Nt (6.d292286f.chunk.js:2:17865)
	(anonymous function) (6.d292286f.chunk.js:2:11082)
	gt (6.d292286f.chunk.js:2:11151)
	promiseReactionJob
```
