### ISSUE TITLE
Latest version seems to ignore CONFIG_FILE env variable

### ISSUE THREAD

**Issue by Gabisonfire** [prymitive/karma#1466]
I have a deployment I used based on the helm chart:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-karma
spec:
  selector:
    matchLabels:
      name: foo-karma
  template:
    metadata:
      labels:
        name: foo-karma
    spec:
      containers:
        - name: foo-karma
          image: lmierzwa/karma
          env:
            - name: CONFIG_FILE
              value: /etc/karma/karma.conf
          volumeMounts:
            - mountPath: /etc/karma
              name: karma-config
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              port: http
          livenessProbe:
            httpGet:
              port: http
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
      volumes:
        - name: karma-config
          configMap:
            name: foo-karma
```

```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: foo-karma
  labels:
    app: foo-karma
data:
  karma.conf: |
    alertmanager:
      interval: 5s
      servers:
        - name: foo-alertmanager
          uri: http://foo-alertmanager-web:9093
    annotations:
      visible:
      - summary
      hidden:
      - description
    labels:
      strip:
      - instance
      - endpoint
      color:
        static:
        - job
        - service
        unique:
        - namespace
        - severity
    filters:
      default:
      - "@state=active"
```

In the deployment, specifying no tags or latest will ignore the CONFIG_FILE environment and use the default config

```
kubectl logs foo-karma-547f497748-kblmt                                                                                                                                
time="2020-02-25T18:48:40Z" level=info msg="Version: f83b124"
time="2020-02-25T18:48:40Z" level=info msg="Parsed configuration:"
time="2020-02-25T18:48:40Z" level=info msg="authentication:"
time="2020-02-25T18:48:40Z" level=info msg="  header:"
[redacted for clarity]
time="2020-02-25T18:48:40Z" level=info msg="  colorTitlebar: false"
time="2020-02-25T18:48:40Z" level=info msg="  theme: auto"
time="2020-02-25T18:48:40Z" level=info msg="  minimalGroupWidth: 420"
time="2020-02-25T18:48:40Z" level=info msg="  alertsPerGroup: 5"
time="2020-02-25T18:48:40Z" level=info msg="  collapseGroups: collapsedOnMobile"
time="2020-02-25T18:48:40Z" level=fatal msg="No valid Alertmanager URIs defined"
```
But specifying other environment variable is taken into account like ALERTMANAGER_URI.
Using v0.55 tag resolves this issue.
