### ISSUE TITLE
Management authentication chart helm

### ISSUE THREAD

**Issue by duthifree** [prymitive/karma#1603]
Hi, 

For authentication we need to add httpHeaders to livenessProbe an readinessProbe

https://github.com/helm/charts/blob/050a109d5a84185e4b12206f14571b319772833f/stable/karma/templates/deployment.yaml#L51-L63

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request

https://github.com/prymitive/karma/blob/v0.56/docs/CONFIGURATION.md#authentication

is it possible to add this for livenessProbe et readinessProbe :

```
        httpHeaders:
        - name: X-Username
          value: kubernetes-probe
```

**Comment by prymitive** [comment]
I'm not sure if I fully follow, there's `/health` ([see docs](https://github.com/prymitive/karma#health-checks)), this doesn't require any authentication

**Comment by duthifree** [comment]
With karma helm chart
when i try to use authentication configuration with `x-auth`
```
authentication:
  header:
    name: X-Username
    value_re: ^(.+)$
```
my container doesn't start because i need to add `httpHeaders` in the livenessProbe and readinessProbe configuration

**Comment by prymitive** [comment]
What is your `livenessProbe` & `readinessProbe`?

**Comment by duthifree** [comment]
actually helm template :

spec.template.spec.container

```
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.delay }}
            periodSeconds: {{ .Values.livenessProbe.period }}
          readinessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.delay }}
            periodSeconds: {{ .Values.livenessProbe.period }}
          resources:
```
