### ISSUE TITLE
Editting a silence results in 404 page not found 

### ISSUE THREAD

**Issue by BenoitKnecht** [prymitive/karma#1646]
In versions 0.59 and 0.60, when I edit or create a silence in Karma (with a single Alertmanager in proxy mode), I get a 404 error after clicking `Submit` on the `Preview silenced alerts` page:

![Screenshot_2020-04-20 karma](https://user-images.githubusercontent.com/1238084/79745491-b18ce780-8308-11ea-8a88-18a8b3d17cfe.png)

I went back a few versions to see when it stopped working:

- *0.56*: works;
- *0.57*: #1573;
- *0.58*: #1573;
- *0.59*: `404 not found`;
- *0.60*: `404 not found`.

**Comment by prymitive** [comment]
Can you open developer tools in your browsers and get the URI it used for that failing request?
What's your alertmanager version?
Can you share your `alertmanager:servers` config?

**Comment by BenoitKnecht** [comment]
The request that returns `404` is a `POST` on `https://karma.example.com/proxy/alertmanager//api/v2/silences`.

The Alertmanager version is 0.20.0, and the `alertmanager:servers` config is

```yaml
alertmanager:
  servers:
  - uri: http://localhost:9093
    external_uri: https://alertmanager.example.com
    proxy: true
```
