### ISSUE TITLE
bug: possible improper URL detection in annotations

### ISSUE THREAD

**Issue by lrstanley** [prymitive/karma#1648]
I'm noticing that description annotations that contain a URL at the start with trailing text will convert the entire description annotation into a URL. This may happen with other annotations (suspect so), but haven't tested.

E.g. this alert:

```yaml
  - alert: BlackboxInstanceDown
    annotations:
      description: '{{ $labels.instance }} in {{ $labels.env }} (job: {{ $labels.job }}) is not successfully probing via the blackbox prober. this could be due to the endpoint being offline, returning an invalid status code, taking too long to respond, etc.'
      summary: 'job {{ $labels.job }} with instance {{ $labels.instance }} failing blackbox probes'
```

Gets converted entirely into a URL:

https://some-links.domain.com/healthcheck%20in%20dev%20(job:%20blackbox)%20is%20not%20successfully%20probing%20via%20the%20blackbox%20prober.%20this%20could%20be%20due%20to%20the%20endpoint%20being%20offline,%20returning%20an%20invalid%20status%20code,%20taking%20too%20long%20to%20respond,%20etc.

and shown in the UI as:
![image](https://user-images.githubusercontent.com/1847365/79790944-84e1cb80-831a-11ea-8806-1917c94626d0.png)

This is likely due to spaces (and a few other chars ofc) being considered valid in a URL, so the entire thing being checked is valid.

I have yet to test if having regular text before **and** after will lead to a similar issue, where trailing text is converted to be part of the URL...

I suspect the solution, if you were to want to fix this (depending on who you listen to, one isn't supposed to have unique label data in the description.. we don't follow this standard though), is to split by spaces first, then compare each item (but not sure how this would look in the UI), or ignore if there are spaces. Not sure if this check is happening in the backend or frontend.
