### ISSUE TITLE
Configuration error since v0.56

### ISSUE THREAD

**Issue by sylr** [prymitive/karma#1665]
I've tried upgrading from v0.53 to v0.60 but I have the following error which started from v0.56.

```
time="2020-04-28T07:35:39Z" level=fatal msg="Failed to unmarshal configuration: 1 error(s) decoding:\n\n* 'Alertmanager.proxy' expected type 'bool', got unconvertible type 'map[string]interface {}'"
```

Here's my config:

```yaml
    alertmanager:
      interval: 10s
      servers:
      - name: k8s11-dev
        uri: http://prometheus-alertmanager-k8s11-dev/k8s11-dev/
        timeout: 10s
        proxy: true
      - name: k8s12-test
        uri: http://prometheus-alertmanager-k8s12-test/k8s12-test/
        timeout: 10s
        proxy: true
      - name: k8s14-prod
        uri: http://prometheus-alertmanager-k8s14-prod/k8s14-prod/
        timeout: 10s
        proxy: true
      - name: k8s15-infra
        uri: http://prometheus-alertmanager-k8s15-infra/k8s15-infra/
        timeout: 10s
        proxy: true
    annotations:
     strip:
     - alert_title_labels
    labels:
      color:
        unique:
        - "@alertmanager"
        - "@receiver"
        - env
        - severity
        - maintainer
        custom:
          severity:
          - value: info
            color: "#87c4e0"
          - value: warning
            color: "#ffae42"
          - value: critical
            color: "#8e44ad"
      strip:
      - pod_template_hash
      - kubernetes_name
      - kubernetes_namespace
      - heritage
      - chart
      - component
      - app
      - release
      - replica
      - beta_kubernetes_io_arch
      - beta_kubernetes_io_instance_type
      - beta_kubernetes_io_os
      - failure_domain_beta_kubernetes_io_region
      - failure_domain_beta_kubernetes_io_zone
      - kubernetes_azure_com_cluster
    filters:
      default:
      - "@state=active"
      - "@receiver=~(pager|sinkhole)"
    custom:
      css: /etc/karma/unsee.css
```
