### ISSUE TITLE
Duplicate silences created

### ISSUE THREAD

**Issue by BenoitKnecht** [prymitive/karma#1878]
I'm not exactly sure when it started happening, but I think it began with version 0.64. When I create a silence in Karma using *Silence this group*, two identical silences end up being created.

It should be noted that I run two Alertmanagers in HA mode, and two instances of Karma behind HAproxy, running on the same VMs as each Alertmanager.

Here's the `alertmanager` section of `karma.yml`, which hasn't changed since 0.63 at least:

```yaml
alertmanager:
  servers:
  - name: default
    uri: http://localhost:9093
    external_uri: https://alertmanager.example.com
    proxy: true
```
