### ISSUE TITLE
Unable to filter by alertname

### ISSUE THREAD

**Issue by Stono** [prymitive/karma#1881]
Hey, 
Firstly, thanks for the app :-)

I've noticed I'm unable to filter by alertname:
![Screenshot 2020-06-23 at 16 02 21](https://user-images.githubusercontent.com/1486729/85420347-fe8c7480-b56a-11ea-80f9-cf5a0618bd65.png)
![Screenshot 2020-06-23 at 16 02 23](https://user-images.githubusercontent.com/1486729/85420351-ff250b00-b56a-11ea-8c37-19c8270fbd50.png)

Any ideas?

Typical alert config: 
```
  - alert: GocdBuildFailure
    expr: |
      platform_stage_status{type="build"} == 0
    labels:
      severity: info
      source: '{{ "{{" }}$labels.app{{ "}}" }}'
      pipeline: '{{ "{{" }}$labels.pipeline{{ "}}" }}'
      stage: '{{ "{{" }}$labels.stage{{ "}}" }}'
    annotations:
      instance: '{{ "{{" }}$labels.pipeline{{ "}}" }}/{{ "{{" }}$labels.stage{{ "}}" }}'
      description: >-
        A build stage in GoCD has either failed to complete, or was cancelled.  Please check the GoCD logs for more information.
      dashboard: https://go.atcloud.io/go/pipeline/activity/{{ "{{" }}$labels.pipeline{{ "}}" }}
      summary: GoCD Build Failure
```

My gut is that it's filtering on label, but there isn't a label for `alertname`
