### ISSUE TITLE
silenceForm required labels

### ISSUE THREAD

**Issue by itatabitovski** [prymitive/karma#2001]
I was not able to find something like this in the configuration.

It would be very useful to be able to select required labels that must be filled in when adding a silence (e.g. team).

Something like:
```yaml
silenceForm:
  required:
    - name:
      value: 
      value_re:
```

**Comment by prymitive** [comment]
You could potentially use [ACLs](https://github.com/prymitive/karma/blob/master/docs/ACLs.md#require-postgresadmins-group-to-always-specify-dbpostgres-in-silences) for that:

```
  - action: requireMatcher
    reason: db users must pass team=db
    scope:
      groups:
        - db
    matchers:
      required:
        - name: team
          value: db
```

**Comment by itatabitovski** [comment]
I have the following ACL, but even if i specify the label team karma prevents adding the silence.
 
```yaml
rules:
  - action: requireMatcher
    reason: must specify label team
    matchers:
      required:
        - name: team
          value: .+
          isRegex: true
```

```
DEBU[0028] [dev] Proxy request /proxy/alertmanager/dev/api/v2/silences
DEBU[0028] ACL 0: isAllowed=false err=silence blocked by ACL rule: must specify label team
WARN[0028] [dev] proxy request 'POST /proxy/alertmanager/dev/api/v2/silences' was blocked by ACL rule: silence blocked by ACL rule: must specify label team
```
