### ISSUE TITLE
Multiple @alertmanager labels not stripped

### ISSUE THREAD

**Issue by dswarbrick** [prymitive/karma#224]
If Karma is configured with multiple alertmanager URLs, it seems that it insists on displaying a `@alertmanager` label for each in the alerts on the dashboard.

I've tried to strip the label, without success.
```yaml
labels:
  strip:
  - "@alertmanager"
```

If only a single alertmanager URL is specified, the label is not shown.
