### ISSUE TITLE
Question: is it possible to filter out alerts from the UI by default?

### ISSUE THREAD

**Issue by mmiller1** [prymitive/karma#2348]
After reading through the docs, I don't see a way to filter out an alert from being displayed in the UI. Is this possible? Our situation is that we have dead man switch alerts for all of our clusters that are always firing, it would be nice to not display these to clean up the UI a bit.

**Comment by prymitive** [comment]
If "by default" you mean a set of default filters then set defaults:

```YAML
filters:
  default:
    - "@state=active"
    - severity=critical
```

If you want to those alerts to never show up in karma then route dead man switch alerts to a receiver that you ignore in karma:

```YAML
receivers:
  strip:
    - deadman
```
