### ISSUE TITLE
Not finding karma.yaml in root

### ISSUE THREAD

**Issue by mh720** [prymitive/karma#261]
Howdy Lukasz, 

Great work on this, I just found out about your work on Karma after CloudFlare. I'm evaluating it now to replace unsee in swarmstack (https://www.youtube.com/watch?v=3FpTcVnvfRg - https://github.com/swarmstack/swarmstack) - which rebuilt Stefan Prodan's swarmprom starter kit for Docker Prometheus/Grafana/Alertmanager/Unsee and adds Docker swarm node installation and ongoing management with ease of installation as a focus. 

Dockerfile below works, but requires addition of the CONFIG_FILE env variable. My reading of docs/CONFIGURATION.md was that Karma would look for a file named karma.yaml in the same directory. Didn't see an existing ticket on this issue, but might be pebkac as I just found out about Karma an hour ago :)

```
#cat docker-compose.yml
version: "3.4"
configs:
  karma-conf:
    file: ./karma/karma.yaml

services:
  karma:
    image: lmierzwa/karma:latest
    configs:
      - source: karma-conf
        target: /karma.yaml
    deploy:
      mode: replicated
      replicas: 1
      labels:
        prometheus.enable: "true"
        prometheus.port: "8080"
        prometheus.path: "/metrics"
    environment:
      - CONFIG_FILE=/karma.yaml
```
