### ISSUE TITLE
Release Notes for v0.78 Healtchchecks is wrong

### ISSUE THREAD

**Issue by gleichda** [prymitive/karma#2700]
[Release 0.78](https://github.com/prymitive/karma/releases/tag/v0.78) states to use 
```
alertmanager:
  servers:
    - name: am
      uri: https://alertmanager.example.com
      healthcheck:
        alerts:
          prom1:
            - alertname=DeadMansSwitch
            - instance=prom1
          prom2:
            - alertname=DeadMansSwitch
            - instance=prom2
```

But according to the struct (and also working) it is
```
alertmanager:
  servers:
    - name: am
      uri: https://alertmanager.example.com
      healthcheck:
        filters:
          prom1:
            - alertname=DeadMansSwitch
            - instance=prom1
          prom2:
            - alertname=DeadMansSwitch
            - instance=prom2
```

So updating the release notes should be enough. -> Replace `alerts` with `filters`
