### ISSUE TITLE
karma hangs after X time with to many files

### ISSUE THREAD

**Issue by jonaz** [prymitive/karma#2888]
Are running 3 karma instances with each 24 alertmanagers. Each one of them are randomly hanging after a day or so. 

Seems to be leaking sockets. Not visibile in netstat but in lsof and /proc/1180/fd

I will try to find the bug myself next week. Just registered it here to check if someone else have seen this? 

```
2021/03/12 11:11:35 http: Accept error: accept tcp [::]:8181: accept4: too many open files; retrying in 1s 
```

lsof:
```
karma       1180 33304 karma                   karma 4088u     sock                0,9        0t0    2245576 protocol: TCPv6
karma       1180 33304 karma                   karma 4089u     sock                0,9        0t0    2245583 protocol: TCPv6
karma       1180 33304 karma                   karma 4090u     sock                0,9        0t0    2226157 protocol: TCPv6
karma       1180 33304 karma                   karma 4091u     sock                0,9        0t0    2246754 protocol: TCPv6
karma       1180 33304 karma                   karma 4092u     sock                0,9        0t0    2229090 protocol: TCPv6
karma       1180 33304 karma                   karma 4093u     sock                0,9        0t0    2239012 protocol: TCPv6
karma       1180 33304 karma                   karma 4094u     sock                0,9        0t0    2239099 protocol: TCPv6
karma       1180 33304 karma                   karma 4095u     sock                0,9        0t0    2246791 protocol: TCPv6
```

/proc/1180/fd
```
lrwx------. 1 karma karma 64 Mar 12 11:16 980 -> 'socket:[1647306]'
lrwx------. 1 karma karma 64 Mar 12 11:16 981 -> 'socket:[1649845]'
lrwx------. 1 karma karma 64 Mar 12 11:16 982 -> 'socket:[1649951]'
lrwx------. 1 karma karma 64 Mar 12 11:16 983 -> 'socket:[1650850]'
lrwx------. 1 karma karma 64 Mar 12 11:16 984 -> 'socket:[1650924]'
lrwx------. 1 karma karma 64 Mar 12 11:16 985 -> 'socket:[1649329]'
lrwx------. 1 karma karma 64 Mar 12 11:16 986 -> 'socket:[1649334]'
lrwx------. 1 karma karma 64 Mar 12 11:16 987 -> 'socket:[1655117]'
lrwx------. 1 karma karma 64 Mar 12 11:16 988 -> 'socket:[1653245]'
lrwx------. 1 karma karma 64 Mar 12 11:16 989 -> 'socket:[1655164]'
lrwx------. 1 karma karma 64 Mar 12 11:16 99 -> 'socket:[1485188]'
lrwx------. 1 karma karma 64 Mar 12 11:16 990 -> 'socket:[1655224]'
lrwx------. 1 karma karma 64 Mar 12 11:16 991 -> 'socket:[1652299]'
lrwx------. 1 karma karma 64 Mar 12 11:16 992 -> 'socket:[1652303]'
lrwx------. 1 karma karma 64 Mar 12 11:16 993 -> 'socket:[1649641]'
lrwx------. 1 karma karma 64 Mar 12 11:16 994 -> 'socket:[1655256]'
lrwx------. 1 karma karma 64 Mar 12 11:16 995 -> 'socket:[1656480]'
lrwx------. 1 karma karma 64 Mar 12 11:16 996 -> 'socket:[1656840]'
lrwx------. 1 karma karma 64 Mar 12 11:16 997 -> 'socket:[1650557]'
lrwx------. 1 karma karma 64 Mar 12 11:16 998 -> 'socket:[1654368]'
lrwx------. 1 karma karma 64 Mar 12 11:16 999 -> 'socket:[1656871]'

```

our karma.yml config: 
```

alertAcknowledgement:
  author: karma-ack
  duration: 1h
  enabled: true
alertmanager:
  interval: 10s
  servers:
  - cluster: alertmanager
    name: asdf1-alertmanager
    proxy: true
    timeout: 10s
    uri: https://alertmanager.asdf1.asdf.se
  - name: asdf1-build001
    proxy: true
    timeout: 10s
    uri: http://k8s-build001-alertmanager.asdf1.asdf.se:9999
  - name: asdf1-dev001
    proxy: true
    timeout: 10s
    uri: http://k8s-dev001-alertmanager.asdf1.asdf.se:9999
  - name: asdf1-infra001
    proxy: true
    timeout: 10s
    uri: http://k8s-infra001-alertmanager.asdf1.asdf.se:9999
  - name: asdf1-lb001
    proxy: true
    timeout: 10s
    uri: http://k8s-lb001-alertmanager.asdf1.asdf.se:9999
  - name: asdf1-rancher
    proxy: true
    timeout: 10s
    uri: http://k8s-rancher-alertmanager.asdf1.asdf.se:9999
  - name: asdf1-acce001
    timeout: 10s
    uri: http://k8s-acce001-alertmanager.asdf1.asdf.se:9999
  - name: asdf1-prod001
    timeout: 10s
    uri: http://k8s-prod001-alertmanager.asdf1.asdf.se:9999
  - cluster: alertmanager
    name: asdf2-alertmanager
    proxy: true
    timeout: 10s
    uri: https://alertmanager.asdf2.asdf.se
  - name: asdf2-build001
    proxy: true
    timeout: 10s
    uri: http://k8s-build001-alertmanager.asdf2.asdf.se:9999
  - name: asdf2-dev001
    proxy: true
    timeout: 10s
    uri: http://k8s-dev001-alertmanager.asdf2.asdf.se:9999
  - name: asdf2-infra001
    proxy: true
    timeout: 10s
    uri: http://k8s-infra001-alertmanager.asdf2.asdf.se:9999
  - name: asdf2-lb001
    proxy: true
    timeout: 10s
    uri: http://k8s-lb001-alertmanager.asdf2.asdf.se:9999
  - name: asdf2-rancher
    proxy: true
    timeout: 10s
    uri: http://k8s-rancher-alertmanager.asdf2.asdf.se:9999
  - name: asdf2-acce001
    timeout: 10s
    uri: http://k8s-acce001-alertmanager.asdf2.asdf.se:9999
  - name: asdf2-prod001
    timeout: 10s
    uri: http://k8s-prod001-alertmanager.asdf2.asdf.se:9999
  - cluster: alertmanager
    name: asdf3-alertmanager
    proxy: true
    timeout: 10s
    uri: https://alertmanager.asdf3.asdf.se
  - name: asdf3-build001
    proxy: true
    timeout: 10s
    uri: http://k8s-build001-alertmanager.asdf3.asdf.se:9999
  - name: asdf3-dev001
    proxy: true
    timeout: 10s
    uri: http://k8s-dev001-alertmanager.asdf3.asdf.se:9999
  - name: asdf3-infra001
    proxy: true
    timeout: 10s
    uri: http://k8s-infra001-alertmanager.asdf3.asdf.se:9999
  - name: asdf3-lb001
    proxy: true
    timeout: 10s
    uri: http://k8s-lb001-alertmanager.asdf3.asdf.se:9999
  - name: asdf3-rancher
    proxy: true
    timeout: 10s
    uri: http://k8s-rancher-alertmanager.asdf3.asdf.se:9999
  - name: asdf3-acce001
    timeout: 10s
    uri: http://k8s-acce001-alertmanager.asdf3.asdf.se:9999
  - name: asdf3-prod001
    timeout: 10s
    uri: http://k8s-prod001-alertmanager.asdf3.asdf.se:9999
labels:
  color:
    custom:
      severity:
      - color: '#87c4e0'
        value: info
      - color: '#ffae42'
        value: warning
      - color: '#ff220c'
        value: critical
    static:
    - job
    unique:
    - host
    - instance
    - label_team
    - team
    - dc
    - '@receiver'
listen:
  address: 0.0.0.0
  port: 8181
  prefix: /
silences:
  comments:
    linkDetect:
      rules:
      - regex: (DRIF-[0-9]+)
        uriTemplate: https://jira.asdf.se/browse/$1
ui:
  alertsPerGroup: 5
  collapseGroups: collapsedOnMobile
  colorTitlebar: false
  hideFiltersWhenIdle: true
  minimalGroupWidth: 420
  multiGridLabel: severity
  multiGridSortReverse: false
  refresh: 10s
  theme: auto

```
