### ISSUE TITLE
custom Slience Management URL when proxy enabled

### ISSUE THREAD

**Issue by orangetangerine** [prymitive/karma#3060]
Hi, I have karma deployed behind a proxy from Rancher.
So the karma URL is something like `https://example.com/k8s/clusters/project/api/v1/namespaces/monitoring/services/http:karma:80/proxy/?q=`

When the proxy mode is enabled, silence management request will be sent to `https://example.com/proxy/alertmanager`,
instead of `https://example.com/k8s/clusters/project/api/v1/namespaces/monitoring/services/http:karma:80/proxy/alertmanager`

Both list alerts and list silence work find, but silence management requests are sent to an invalid URL.

I found the code that returning InternalURI wrote:
https://github.com/prymitive/karma/blob/main/internal/alertmanager/models.go#L183-L195
```go
// InternalURI is the URI of this Alertmanager that will be used for all request made by the UI
func (am *Alertmanager) InternalURI() string {
	if am.ProxyRequests {
		sub := fmt.Sprintf("/proxy/alertmanager/%s", am.Name)
		if strings.HasPrefix(config.Config.Listen.Prefix, "/") {
			return path.Join(config.Config.Listen.Prefix, sub)
		}
		return path.Join("/"+config.Config.Listen.Prefix, sub)
	}

	// strip all user/pass information, fetch() doesn't support it anyway
	return uri.WithoutUserinfo(am.PublicURI())
}
```

It would be nice if InternalURI can be customized. And if no customized URL is specified, fallback to this code, for backward-compatible

**Comment by orangetangerine** [comment]
#3063

**Comment by orangetangerine** [comment]
Here is how karma run in my K8S:
```yaml
      containers:
      - args:
        - --alertmanager.proxy
        - --alertmanager.uri
        - http://alertmanager-operated.cattle-prometheus.svc:9093
        - --alertmanager.name
        - xxx
        - --alertmanager.cors.credentials
        - same-origin
        - --alertmanager.internal_uri_prefix
        - /k8s/clusters/project/api/v1/namespaces/monitoring/services/http:karma:80/proxy
```

Silent Management works as expected.

The URL sent to from the browser looks like
`https://example.com/k8s/clusters/{project}/api/v1/namespaces/monitoring/services/http:karma:80/proxy/proxy/alertmanager/{alertmanager_name}/api/v2/silence/5adbc660-0a66-42f6-b54c-7385ef3ea3e8`

**Comment by prymitive** [comment]
> When the proxy mode is enabled, silence management request will be sent to https://example.com/proxy/alertmanager,
instead of https://example.com/k8s/clusters/project/api/v1/namespaces/monitoring/services/http:karma:80/proxy/alertmanager

That's expected, `/proxy/$name` endpoint handles those requests and all it needs is the alertmanager name. It's not a proxy in a sense that it will forward any request to any endpoint keeping paths and everything else as is.

**Comment by prymitive** [comment]
If you want different URI to be used between karma->alertmanager and ui->alertmanager then you can set `external_uri`, there's a breakdown of all combinations of values on [CONFIGURATION.md#alertmanagers](https://github.com/prymitive/karma/blob/main/docs/CONFIGURATION.md#alertmanagers)

**Comment by prymitive** [comment]
Can you share your config? After re-reading it seems that you're saying that `listen.prefix` doesn't work for proxied silences.

**Comment by orangetangerine** [comment]
Thanks for the quick reply.

In my case, https://example.com is my Rancher's homepage. https://example.com/proxy/alertmanager points to nothing.

`https://example.com/k8s/clusters/{project}/api/v1/...` is the way to access Prometheus, Kiali, Jaeger in our cluster, here is the rancher's page:

![1](https://user-images.githubusercontent.com/4987543/116867976-8853a680-ac40-11eb-91b8-d1a8da91f067.png)

Authentication is done by Rancher. And this is the only way we access prometheus and other 3rd UI (except kubectl port-forward)

Here is how our Jaeger UI pass request via Browser:
`https://example.com/k8s/clusters/{project}/api/v1/namespaces/istio-system/services/http:tracing:80/proxy/jaeger/search?end=1620039159261000&limit=20&lookback=1h&maxDuration=10s&minDuration&service=istio-ingressgateway&start=1620035559261000&tags=%7B%221%22%3A%22true%22%7D`

Nginx is integrated into rancher, request is pass to backend host after rewrite_url.


I've tried listen.prefix, external_uri and other kinds of combination, none of those worked:
1. if listen.prefix is set, Karma UI can not be accessed. Since all uri between `example.com/' and `.../proxy` is rewrote to before sent to Karma.
2. If external_url is used and set to sth like `/k8s/cluster/...`, then `List Silence` is done via the Internet instead of cluster internal access. (I've tried, there was another problem but I can remind);
3. If external_url is used and set to `http://alertmanager-operated.cattle-prometheus.svc:9093` (cluster internal access), there would be CROS problem

My exec config is list above:
```yaml
      containers:
      - args:
        - --alertmanager.proxy
        - --alertmanager.uri
        - http://alertmanager-operated.cattle-prometheus.svc:9093
        - --alertmanager.name
        - xxx
        - --alertmanager.cors.credentials
        - same-origin
        - --alertmanager.internal_uri_prefix
        - /k8s/clusters/project/api/v1/namespaces/monitoring/services/http:karma:80/proxy
```

And the Karma UI URL is:
`https://example.com/k8s/clusters/{project}/api/v1/namespaces/monitoring/services/http:karma:80/proxy/?q=`

As I mentioned above, if add internal_uri_prefix, the POST request is sent to 
`https://example.com/k8s/clusters/{project}/api/v1/namespaces/monitoring/services/http:karma:80/proxy/proxy/alertmanager/{alertmanager_name}/api/v2/silence/5adbc660-0a66-42f6-b54c-7385ef3ea3e8`

I believed that what Karma received would be `https://example.com/proxy/alertmanager/{alertmanager_name}/...`, since the uri `/k8s/...` is rewrote/removed by rancher/Nginx

I am not an English speaker, Hope I explain well why I did this :(
