### ISSUE TITLE
Support external_uri and uri for prometheus in alert history

### ISSUE THREAD

**Issue by timown** [prymitive/karma#3064]
Any chance to support basically pretty same setup as with alertmanagers?
The `source` label has the external_uri which is behind oauth-proxy so karma can't query it

**Comment by prymitive** [comment]
I can add some config to rewrite source via static mapping or regexes, something like:

```YAML
history:
  rewrite:
    - source: http://prom.example.com
      uri: http://prom.internal
    - source: http://(.+).prom.example.com
      uri: http://prometheus-$1.internal
```
