### ISSUE TITLE
Problem when silencing alerts to alertmanager with name containing space

### ISSUE THREAD

**Issue by spinus** [prymitive/karma#3651]
**What happened?**

I got alert so I click to silence specific one and I dropped most labels (just for sake of example):

![image](https://user-images.githubusercontent.com/950799/138721454-7ccb40a0-ed22-453a-9887-19b2a6e3ae96.png)

When I click preview, karma doesn't show any alerts

![image](https://user-images.githubusercontent.com/950799/138721515-7332b049-c32e-45cd-b6ac-f7361b0eb968.png)

When I click "submit" it shows the error:

![image](https://user-images.githubusercontent.com/950799/138721904-9ffab929-d13c-4dd6-bfbc-cb30e70bd1e0.png)

In the browser network tab it tells 404 for proxy endpoint. It properly encodes space as %20, but maybe that's the issue?

**Did you expect to see something different?**

I would expect that silence is properly set

**How to reproduce it (as minimally and precisely as possible)**:

* Manifests:

```
# karma config
---
apiVersion: v1
data:
  karma.yaml: |-
    alertmanager:
      interval: 10s
      servers:
        - name: aws-prod-database (app)
          uri: https://[REDACTED]
          timeout: 10s
          proxy: true

```

What worked:
- removing the space solves the problem with sending the silence request (it sends correctly and karma screen shows big green thing)
- removing the space does not help for "preview" screen, it still doesn't show any matching alerts
- removing parenthesis helps for "preview" screen and matching alerts are properly shown
