### ISSUE TITLE
Alert history doesn't work with vmalerts

### ISSUE THREAD

**Issue by timurkhisamov** [prymitive/karma#3684]
`history:` feature doesn't work with victoria-metrics (vmalert)

in source: `https://mon.work.com:4443/vmalert/api/v1/5779816242126150950/13487346302778734963/status`
karma logs:
```
level=error msg="History query failed" error="failed to query Prometheus for label names: bad_response: readObjectStart: expect { or n, but found r, error found in #1 byte of ...|remoteAddr:|..., bigger context ...|remoteAddr: \"127.0.0.1:44094\"; requestURI: /api/v1/|..." labels={"alertname":"VictoriaMetricsTooManyLogs","severity":"warning"} uri=https://mon.cinarra.com:4443/vmalert/api/v1/5779816242126150950/13487346302778734963/status worker=3
```
nginx logs:
```
10.10.19.204 - - [02/Nov/2021:14:23:50 +0000] "GET /vm/api/v1/5779816242126150950/3223283294973603054/status/api/v1/labels?end=1635837685.4391422&match%5B%5D=%7B__name__%3D%22ALERTS_FOR_STATE%22%7D&start=16358
37385.439142 HTTP/1.1" 400 311 "-" "curl/7.29.0" "-"
```
karma configs:
```
history:
  enabled: true
  timeout: 20s
  workers: 30
#  rewrite:
#    - source: 'https://mon.work.com:4443/vmalert'
#      uri: 'https://mon.work.com:4443/vm'
```

I've tried with rewrite rules and without it.
