### ISSUE TITLE
[Clarification] Configuration of groups via external Autho provider,

### ISSUE THREAD

**Issue by Cellebyte** [prymitive/karma#3702]
Hey I'am currently trying to configure the `X-Auth-User` and `X-Auth-Groups` as it is part of your documentation.
I am stumbling now with configuration issues.

This is my configuration so far.
```yaml
alertmanager:
  interval: 2m
  servers:
  - cluster: example
    external_uri: https://alertmanager.example.com
    healthcheck:
      filters:
        prometheus:
        - alertname=Watchdog
        - prometheus=monitoring-system/prometheus-prometheus
      visible: true
    name: alertmanager-0
    proxy: false
    readonly: false
    timeout: 30s
    uri: http://alertmanager-alertmanager-alertmanager-0.alertmanager-operated.monitoring-system.svc
  - cluster: example
    external_uri: https://alertmanager.example.com
    healthcheck:
      filters:
        prometheus:
        - alertname=Watchdog
        - prometheus=monitoring-system/prometheus-prometheus
      visible: true
    name: alertmanager-1
    proxy: false
    readonly: false
    timeout: 30s
    uri: http://alertmanager-alertmanager-alertmanager-1.alertmanager-operated.monitoring-system.svc
  - cluster: example
    external_uri: https://alertmanager.example.com
    healthcheck:
      filters:
        prometheus:
        - alertname=Watchdog
        - prometheus=monitoring-system/prometheus-prometheus
      visible: true
    name: alertmanager-2
    proxy: false
    readonly: false
    timeout: 30s
    uri: http://alertmanager-alertmanager-alertmanager-2.alertmanager-operated.monitoring-system.svc
authentication:
  header:
    group_name: X-Auth-Groups
    group_value_re: 'Groups: (.+)'
    group_value_separator: ','
    name: X-Auth-User
    value_re: ^(.+)$
authorization:
  acl:
    silences: /etc/karma/acls.yaml
  groups:
  - name: admin
    members: []
  - name: emergency
    members: []
debug: false
filters:
  default:
  - '@receiver=by-cluster-service'
karma:
  name: karma-schiff
labels:
  color:
    static:
    - job
    - cluster
    unique:
    - cluster
    - instance
    - '@receiver'
  keep: []
  strip: []
listen:
  prefix: /karma
log:
  config: false
  level: info
receivers:
  keep: []
  strip: []
silenceForm:
  strip:
    labels:
    - job
silences:
  comments:
    linkDetect:
      rules:
      - regex: PROJECT-[0-9]+
        uriTemplate: https://jira.example.com/browse/$1
      - regex: PROJECTX-[0-9]+
        uriTemplate: https://jira.example.com/browse/$1
ui:
  alertsPerGroup: 5
  collapseGroups: collapsedOnMobile
  colorTitlebar: false
  hideFiltersWhenIdle: true
  minimalGroupWidth: 420
  refresh: 30s

```
