### ISSUE TITLE
I get "NetworkError when attempting to fetch resource" when trying to silence an alert

### ISSUE THREAD

**Issue by ekartsonakis** [prymitive/karma#3761]
I see no logs in the pod of karma to understand what is the problem. Here is my current config:

```
    alertmanager:
      interval: 30s
      servers:
      - name: prometheus-01
        timeout: 10s
        proxy: false
        readonly: false
        uri: http://cmpadmin:******@prometheus-01.prod.xxxxx.eu:9093
    listen:
      address: 0.0.0.0
      port: 8080
      prefix: /
```       
Prometheus is running out of kubernetes but I can see active alarms in karma gui without a problem.
