### ISSUE TITLE
Can't delete silences from Karma

### ISSUE THREAD

**Issue by moonbaseDelta** [prymitive/karma#3831]
Hi all, I'm using Karma `v0.93-79-ga2e1f78` with HTTPS on both Karma and Alertmanager. It works fine until I try to delete a silence. 

The errors I get in browser console look like that:
```
Access to fetch at 'https://<my_prom_host>:9093/api/v2/silence/54b5d366-cf98-4ef9-9f07-39ef6378b3d6' from origin 'https://<my_karma_host>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
useFetchDelete.ts:31 DELETE https://<my_prom_host>:9093/api/v2/silence/54b5d366-cf98-4ef9-9f07-39ef6378b3d6 net::ERR_FAILED
```

Karma's config looks like this:
```
listen:
  port: <karma_port>
  tls:
    cert: "<cert_path>"
    key:  "<key_path>"
alertmanager:
  servers:
  - name: <my_prom_host>
    uri: "https://<my_prom_host>:9093"
    cors:
      credentials: "omit"
...
```

I've tried adding headers from the config, and using nginx for reverse proxy at Karma's side with proper headers, yet all of that gives me CORS error on DELETE request. 

What could be the problem?
