### ISSUE TITLE
Got status 404 when submit a silence request.

### ISSUE THREAD

**Issue by tuxknight** [prymitive/karma#386]
alertmanager version

``
alertmanager, version 0.15.2 (branch: HEAD, revision: d19fae3bae451940b8470abb680cfdd59bfa7cfa)
  build user:       root@3101e5b68a55
  build date:       20180814-10:53:39
  go version:       go1.10.3
``
alertmanager has command line options ``--web.external-url=https://prom.ctcfin.com/am --web.route-prefix=am`` 

karma version ``"v0.21"``

karma config

```yaml
alertmanager:
  interval: 15s
  servers:
    - name: alertmanager-headq
      uri: http://1.2.3.4:9093/am/
      timeout: 10s
      proxy: true
debug: true
labels:
  color:
    static:
      - job
    unique:
      - instance_ip
      - app_name
      - env

  keep: []
  strip: []
listen:
  address: "0.0.0.0"
  port: 6677
  prefix: /alert
log:
  config: false
  level: debug
receivers:
  keep: []
  strip: []
```
When I try to add a silence request in karma, the following url returns a 404 response:

https://karma.example.com/alert/proxy/alertmanager/alertmanager-idc/api/v1/silences

And when I set the proxy off, a CORS issue comes up.
