### ISSUE TITLE
multiGridLabel issue

### ISSUE THREAD

**Issue by vDMG** [prymitive/karma#4028]
Hello, 

First of all thanks for this really cool tool :smile: 

I'm trying to use `multiGridLabel` feature but impossible to make it work. 

I've tried using `cluster` or `@cluster` but none of those works.

It may be related because I have two similar labels ? `cluster` and `@cluster` ?

Thank you for your help !

## Configuration 
Karma version >= 0.98

```
ui:
  theme: dark
  multiGridLabel: cluster
  multiGridSortReverse: true
alertmanager: 
  interval: 30s
  servers:
  [...]
```
## Screenshot

![image](https://user-images.githubusercontent.com/11329133/156204200-566c894a-5593-4198-87b9-3a6a9372df30.png)
