### ISSUE TITLE
make it possible to skip tls validation of https alertmanager backend

### ISSUE THREAD

**Issue by davidkarlsen** [prymitive/karma#409]
Our alertmanager instance comes with self-signed certs by vendor (IBM ICP).
It would be nice if you could provide a flag to skip validation of certificate.
I could not find any env var to set this which go would act on - so it seems it has to be coded as an option/flag to pass.

```
Get https://monitoring-prometheus-alertmanager.kube-system:9093/alertmanager/api/v1/silences: x509: certificate signed by unknown authority
```

**Comment by prymitive** [comment]
Any chance you can build code from #410 to verify that it works for you? I made a quick PR while waiting on a train, so not 100% sure if it covers everything. Thanks!

**Comment by davidkarlsen** [comment]
No cigar so far, I checked out the branch, did `make docker-image` and updated the manifest:
```
- env:
    - name: ALERTMANAGER_URI
      value: https://monitoring-prometheus-alertmanager.kube-system:9093/alertmanager
    - name: ALERTMANAGER_TLS_INSECURE_SKIP_VERIFY
      value: "true"
    - name: ALERTMANAGER_TLS_INSECURESKIPVERIFY
      value: "true"
    image: fsnexus.evry.com:8085/evryfs/karma:v0.22-17-gb0fc4fc
    imagePullPolicy: IfNotPresent
```

but  still the same

**Comment by prymitive** [comment]
It only works with a config file (if at all), I can add a flag for single am mode

**Comment by davidkarlsen** [comment]
```
 configMap:
      enabled: true
      rawConfig:
        alertmanager:
          interval: 60s
          servers:
          - name: icp-alert-manager
            uri: https://monitoring-prometheus-alertmanager.kube-system:9093/alertmanager
            tls:
              insecureSkipVerify: true

```
```
time="2019-02-01T16:16:31Z" level=error msg="[icp-alert-manager] request to https://monitoring-prometheus-alertmanager.kube-system:9093/alertmanager/api/v1/silences failed with 400 Bad Request"
```
