### ISSUE TITLE
start karma faild , log: ]

### ISSUE THREAD

**Issue by hongruiji** [prymitive/karma#4220]
config : 
```yaml
authentication:
  basicAuth:
    users:
      - username: admin
        password: password
      - username: view
        password: view
authorization:
  acls:
    silences: '/etc/karma/acls.yaml'
  groups:
    - name: admins
      members:
        - admin
    - name: users
      members:
        - view
```

Start falid , 

```yaml
authentication:
  basicAuth:
    users:
      - username: admin
        password: password
      - username: view
        password: view
authorization:
#  acls:
#    silences: '/etc/karma/acls.yaml'
  groups:
    - name: admins
      members:
        - admin
    - name: users
      members:
        - view
```
start ok . 

* acls.yaml: 
```yaml
rules:
  - action: allow
    reason: admins are allowed
    scope:
      groups:
        - admins
```

start filed log: 

ound in type struct { Groups []config.AuthorizationGroup; ACL struct { Silences string } \"yaml:\\\"acl\\\" koanf:\\\"acl\\\"\" }"
level=fatal msg="Execution failed" error="failed to parse configuration file \"/etc/karma/karma.yaml\": yaml: unmarshal errors:\n  line 28: field acls not found in type struct { Groups []config.AuthorizationGroup; ACL struct { Silences string } \"yaml:\\\"acl\\\" koanf:\\\"acl\\\"\" }"
level=fatal msg="Execution failed" error="failed to parse configuration file \"/etc/karma/karma.yaml\": yaml: unmarshal errors:\n  line 28: field acls not found in type struct { Groups []config.AuthorizationGroup; ACL struct { Silences string } \"yaml:\\\"acl\\\" koanf:\\\"acl\\\"\" }"
level=fatal msg="Execution failed" error="failed to parse configuration file \"/etc/karma/karma.yaml\": yaml: unmarshal errors:\n  line 28: field acls not found in type struct { Groups []config.AuthorizationGroup; ACL struct { Silences string } \"yaml:\\\"acl\\\" koanf:\\\"acl\\\"\" }"
level=fatal msg="Execution failed" error="failed to parse configuration file \"/etc/karma/karma.yaml\": yaml: unmarshal errors:\n  line 28: field acls not found in type struct { Groups []config.AuthorizationGroup; ACL struct { Silences string } \"yaml:\\\"acl\\\" koanf:\\\"acl\\\"\" }"
level=fatal msg="Execution failed" error="failed to parse configuration file \"/etc/karma/karma.yaml\": yaml: unmarshal errors:\n  line 28: field acls not found in type struct { Groups []config.AuthorizationGroup; ACL struct { Silences string } \"yaml:\\\"acl\\\" koanf:\\\"acl\\\"\" }"

**Comment by hongruiji** [comment]
https://github.com/prymitive/karma/blob/main/docs/CONFIGURATION.md#alert-acknowledgement

```yaml
authentication:
  basicAuth:
    users:
      - username: alice
        password: secret
      - username: bob
        password: secret
      - username: john
        password: secret
authorization:
  acls:    # Example Error   acl  not acls 
    silences: /etc/karma/acls.yaml
  groups:
    - name: admins
      members:
        - alice
        - bob
    - name: users
      members:
        - john
```
