### ISSUE TITLE
Feature Request - Filter Out Specific `Label=Value` From the UI By Default

### ISSUE THREAD

**Issue by jacklozano** [prymitive/karma#4395]
As a feature request, I would to be able to configure removing certain `label=value` pairs by default in the karma UI.  Similar to hwo we can filter our certain labels:

```
    labels:
      keep: []
      strip:
        - task_id
```

One could go a step deeper and specify what `label=value` pair we want stripped from the UI
