### ISSUE TITLE
alertsPerGroup cannot be bigger than 10

### ISSUE THREAD

**Issue by micborens** [prymitive/karma#4420]
Hello, 

I'm getting this error on web Ui when alertsPerGroup is configured with an int bigger than 10.
In my config, it was configured to 20
![image](https://user-images.githubusercontent.com/3457770/174982036-6bdf57cb-55d2-4762-b188-8ba76f9fe993.png)

```yaml
    ui:
      refresh: 30s
      theme: dark
      hideFiltersWhenIdle: true
      colorTitlebar: false
      minimalGroupWidth: 420
      alertsPerGroup: 20
      collapseGroups: collapsed
```

Since I changed it to 10 I don't the error but i would like to have more than 10 alerts on each group.
