### ISSUE TITLE
Proxy configuration is not used when History is fetched

### ISSUE THREAD

**Issue by tolleiv** [prymitive/karma#4496]
When using a proxy configuration for an alertmanager, history workers won't use the proxy but try to access the alertmanager directly. This is somewhat similar to [#3707](https://github.com/prymitive/karma/issues/3707)

Example configuration:

```
alertmanager:
    interval: 60s
    servers:
        - name: dev-cbk
          uri: https://prometheus-alertmanager.example.oirg/
          proxy: true
          proxy_url: socks5://service-account-token.interal.svc:80
          tls:
            insecureSkipVerify: true
history:
     enabled: true
     timeout: 5s
     workers: 3
```
