### ISSUE TITLE
linkDetect only applies the first rule

### ISSUE THREAD

**Issue by heapdavid** [prymitive/karma#4693]
Hi,

When i set up multiple linkDetect rules, only the first one works. In the example below, only the first rule creates links. If I comment out the first rule, then the second works fine.

Using v0.108

```
silences:
  comments:
    linkDetect:
      rules:
        - regex: "#([0-9]{2,5})"
          uriTemplate: https://gitlab.example.com/issues/$1
        - regex: "#([0-9]{6,})"
          uriTemplate: https://helpdesk.example.com/ticket.html?id=$1
```
