### ISSUE TITLE
Annotation hidden on groups

### ISSUE THREAD

**Issue by bsamsom** [prymitive/karma#4892]
in Karma V109 we are seeing some weird behaviour with the summary annotations in groups.
We have the following set so the summary annotation should always be visible:
```
    annotations:
      default:
        hidden: false
      visible:
        - summary
      order:
        - summary
```

but weve noticed that on `grouped` alerts, if the summary annotation is `unique it shows up`, but if its the `same for all group members` it moves to the bottom of the card and you can `only see it by clicking the plus`. This is unexpected behaviour as we have the app configured to always show summary annotation.

example:
![summary-1](https://user-images.githubusercontent.com/16020228/205088389-fe6d0ae6-b896-4444-ad59-1c623831eea9.jpg)
There is no summary annotation displayed.

but if we click on the plus:
![summary-2](https://user-images.githubusercontent.com/16020228/205088512-9a6e6f95-e4f0-48ea-b8f1-2448aa5b3188.jpg)
The summary annotation appears.

**Comment by prymitive** [comment]
> This is unexpected behaviour as we have the app configured to always show summary annotation.

From https://github.com/prymitive/karma#alert-groups

`Labels and annotations that are shared between all alerts are moved to the footer.`

**Comment by bsamsom** [comment]
@prymitive is there a config option to always show the footer?

This seems unexpected, as its set to always show summary but doesnt always show the summary(as its hidden on the footer).

**Comment by prymitive** [comment]
I'm not sure if I follow.
Are you saying config options:

```
annotations:
      default:
        hidden: false
      visible:
        - summary
      order:
        - summary
```

don't work correctly

OR

are you just surprised that annotations are deduplicated?

**Comment by bsamsom** [comment]
What im saying is that with: 

```
annotations:
      default:
        hidden: false
      visible:
        - summary
      order:
        - summary
```

![summary-1](https://user-images.githubusercontent.com/16020228/205134292-f7d19c62-b0ee-48f6-b56e-cab581868489.jpg)

The summary isnt actually shown on the alert until you expand the alert, the way id expect it to work would be to see the summary without needding to expand the alert.


My assumption would be that:
```
      visible:
        - summary
```

Would have every alert show the summary by default without needed to expand it.

**Comment by prymitive** [comment]
I can't reproduce that

I've updated https://github.com/prymitive/karma/blob/main/demo/karma.yaml#L37 to include

```
annotations:
  default:
    hidden: false
  visible:
    - summary
  order:
    - summary
```

and after running `make run-demo` I see this:
<img width="456" alt="Screenshot 2022-12-01 at 18 55 57" src="https://user-images.githubusercontent.com/114288/205140729-72f2ac63-7922-4f5f-a691-b124db89b783.png">

<img width="452" alt="Screenshot 2022-12-01 at 18 55 39" src="https://user-images.githubusercontent.com/114288/205140718-28ed6568-f5dc-4ed6-812b-7d89d48871b6.png">

Which seems correct.

And when I update the config to hide by default:

```
annotations:
  default:
    hidden: true
  visible:
    - summary
  order:
    - summary
```

I'm seeing this:

<img width="451" alt="Screenshot 2022-12-01 at 19 20 21" src="https://user-images.githubusercontent.com/114288/205141049-5bdf525e-a0cc-4833-a25c-e4c9a2ac9436.png">
<img width="454" alt="Screenshot 2022-12-01 at 19 20 39" src="https://user-images.githubusercontent.com/114288/205141053-a5b9d1b7-6bad-4449-9365-58c100c8f0c6.png">

Which also seems fine.
