### ISSUE TITLE
Alertmanager Consul discovery

### ISSUE THREAD

**Issue by ricardoleal** [prymitive/karma#4925]
Is possible to scrape `alertmanger` targets using `consul` discovery ?

Prometheus example:
```
scrape_configs:
  - job_name: 'haproxy'
    consul_sd_configs:
    - server: 'localhost:8500'
      services:
        - 'haproxy_exporter'
``` 
I think this can be useful to add `alertmanager` instances running in `aws ec2` or `k8s`.
