### ISSUE TITLE
Change Textsize for server badge.

### ISSUE THREAD

**Issue by stratanic** [prymitive/karma#5152]
Hello,  thank you for this well done tool.

Anyone have a tips to change with css the text size ? 
Can anyone give more detailed instructions on how to change the custom Css?
I would like to change the text size for the SERVER! (label vm_name for me)
or a guide to get started on changing the css.

this part is not reallt detailled
custom:
  css: /theme/custom.css
  js: /assets/custom.js

thank you very much

**Comment by stratanic** [comment]
Ok, I found It !! My tips color a label with Karma config file (karma.yml) :  
----------------------------------------
```
labels:
  color:
    custom:
      vm_name:
        - value_re: '.*'
          color: "#e6e"      ----> pink color for vm name
      severity:
        - value: info
          color: "#87c4e0"
        - value: warning
          color: "#ffae42"
        - value: critical
          color: "#ff220c"
```
----------------------------------------

and search a Css selector : I use the end of attribute of "style=" :     span[style$=
(list of CSS selector = www.w3schools.com/cssref/css_selectors.php)
My Css file :  "custom.css"
----------------------------------------
```
span[style$="238);"] {
  font-size: 1.2em !important;
}
```
----------------------------------------

at the end of karma config, just add this  and restart karma service:
----------------------------------------
```
custom:
  css: /usr/share/prometheus/alertmanager/theme/custom.css
```
----------------------------------------


![image](https://user-images.githubusercontent.com/128167842/230744410-f3d73702-0d49-4949-b823-8a31ed58cd32.png)
