### ISSUE TITLE
can not add silence!

### ISSUE THREAD

**Issue by yuchunyun** [prymitive/karma#5253]
Version：
Alertmanager: prom/alertmanager:v0.25.0
Karma: ghcr.io/prymitive/karma:latest
kubernetes: v1.22.2

deploy:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karma
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karma
  template:
    metadata:
      labels:
        app: karma
    spec:
      containers:
      - name: karma
        image: ghcr.io/prymitive/karma:latest
        env:
          - name: ALERTMANAGER_URI
            value: http://192.168.120.53:80
          - name: LOG_LEVEL
            value: debug
```

I got an error when I created a new silence through karma UI like this
![image](https://github.com/prymitive/karma/assets/45453883/05cc90ce-2e98-4154-8cbc-17aae27e0360)
![image](https://github.com/prymitive/karma/assets/45453883/76fe31c5-43c9-4af5-a0b6-0fdcc4b8fb43)
And I don't see anything unusual in karma pod log
I can create silence through alertmanager UI
