### ISSUE TITLE
CONFIG_FILE is half read

### ISSUE THREAD

**Issue by MolinaRomain** [prymitive/karma#5270]
Hi, I have this Config-map  
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: karma-conf
  labels:
    name: karma-conf
data:
  karma.yaml: |-
    alertmanager:
      interval: 60s
      servers:
        - name: foo-alertmanager
          uri: http://foo-alertmanager-web:9093
          timeout: 10s
          proxy: true
          readonly: false
    annotations:
      default:
        hidden: false
      hidden : []
      visible:
        - summary
      keep: []
    filters:
      default:
        - "@state=active"
        - severity=critical
    grid:
      sorting:
        order: label
        reverse: false
        label: severity
        customValues:
          labels:
            severity:
              critical: 1
              warning: 2
              info: 3
    history:
      enabled: false
    labels:
      color:
        custom:
          severity:
            - value: info, fatal
              color: "#87c4e0"
            - value: warning
              color: "#ffae42"
            - value: critical
              color: "#ff220c"
            - value_re: ".*"
              color: "#736598"
    listen:
      address: "0.0.0.0"
      port: 8080
      prefix: /
      tls:
        cert: ""
        key: ""
      cors:
        allowedOrigins: []
    log:
      config: false
      level: info
    ui:
      refresh: 60s
      hideFiltersWhenIdle: true
      colorTitlebar: false
      theme: "light"
      animations: true
      minimalGroupWidth: 420
      alertsPerGroup: 5
      collapseGroups: collapsedOnMobile
      multiGridLabel: ""
      multiGridSortReverse: false
``` 
And this deployment : 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karma
spec:
  selector:
    matchLabels:
      app: karma
  template:
    metadata:
      labels:
        app: karma
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - monitoring
      containers:
        - name: karma
          image: lmierzwa/karma
          env:
            - name: CONFIG_FILE
              value: "/etc/karma/karma.yaml"
            # - name: UI_THEME
            #   value: "light"
          volumeMounts:
            - mountPath: /etc/karma
              name: karma-conf-volume
          ports:
            - containerPort: 8080
      volumes:
        - name: karma-conf-volume
          configMap:
            name: karma-conf

``` 
For some reason when I change the URI in the config-map it detects it and it doesn't work anymore (as intended) but it is the only thing that is actually used... when I'm changing the ui theme from light to dark or vice versa it doesn't work, and it's pretty much the same for all of the values except the ones in alertmanager:
I am new to Kube and monitoring in general so it might just be a very simple mistake 
![image](https://github.com/prymitive/karma/assets/56554300/4a02b5d5-ee14-4a6f-852e-7954acdabc2f)
For the record I took the latest version.
AlertManager Version : 0.24.0

EDIT : 

I even simplified it just to see if it worked and well, it doesn't with only this is the config file : 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: karma-conf
  labels:
    name: karma-conf
data:
  karma.yaml: |-
    alertmanager:
      interval: 60s
      servers:
        - name: foo-alertmanager
          uri: http://foo-alertmanager-web:9093
          timeout: 10s
          proxy: true
          readonly: false
    ui:
      refresh: 60s
      theme: "light"
 
``` 
Also I took the v0.114 version

**Comment by MolinaRomain** [comment]
I even simplified it just to see if it worked and well, it doesn't with only this is the config file : 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: karma-conf
  labels:
    name: karma-conf
data:
  karma.yaml: |-
    alertmanager:
      interval: 60s
      servers:
        - name: foo-alertmanager
          uri: http://foo-alertmanager-web:9093
          timeout: 10s
          proxy: true
          readonly: false
    ui:
      refresh: 60s
      theme: "light"
 
```
