### ISSUE TITLE
Custom colors wildcard

### ISSUE THREAD

**Issue by TarekAS** [prymitive/karma#537]
We should be able to specify a wildcard in the custom colors dict. This allows us to set a custom color for the all the label values. Useful to change the default static color.
```
labels:
  color:
    custom:
      severity:
        info: "#87c4e0"
        warning: "#ffae42"
        critical: "#ff220c"
        "*": "#ffffff"
```

**Comment by prymitive** [comment]
I was initially concerned that `*` would conflict with label named `*`, but after double checking docs it's clear that 
`*` is [not a valid label name](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels), so that seems doable the way you propose.
I also think it's a good idea to better support `static` colors. I'll try adding it. Thanks!

**Comment by prymitive** [comment]
Raised #540

**Comment by prymitive** [comment]
Waaait, `*` is not a valid *name*, but this is for *values*, and `*` is a valid value, seems like an uncommon one, but valid.
For a proper support, one that doesn't conflict with label values, I'll need to turn configuration section into a list of dicts, so more that a key/val pair can be stored, something like:

```YAML
labels:
  color:
    custom:
      severity:
         - value: info
            color: "#87c4e0"
         - value: warning
            color: "#ffae42"
         - value: critical
            color: "#ff220c"
         - regex: ".*"
            color: "#ffffff"
```
