### ISSUE TITLE
enable actions

### ISSUE THREAD

**Issue by vasyakrg** [prymitive/karma#5640]
how enable action link ?

from alert rules:
```
    - alert: Node LowDiskSpace
      expr: node_filesystem_avail_bytes{mountpoint!~"(^/etc.*|^/run.*|^/.+/dev.*|^/.+/sys.*|^/boot.*)"} / node_filesystem_size_bytes{mountpoint!~"(^/etc.*|^/run.*|^/.+/dev.*|^/.+/sys.*|^/boot.*)"} * 100 < 20 > 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Out of disk space on '{{ $labels.mountpoint }}'"
        description: "Out of disk space on '{{ $labels.mountpoint }}' Node: {{ $labels.node }}. {{ humanize $value }}% left"
        jira: https://123.ru
```

from confif karma:

```
  annotations:
    default:
      hidden: true
    hidden: []
    visible:
      - summary
      - jira
    order:
      - summary
      - description
      - help
    actions:
      - jira
```

but now visible link:
![изображение](https://github.com/prymitive/karma/assets/3581271/01234fda-6c42-4a5e-b133-f2970dd4af28)
