### ISSUE TITLE
karma doesn't shows alerts when one of multiple alertmanagers is offline

### ISSUE THREAD

**Issue by oOHenry** [prymitive/karma#5782]
When one of in my case two alertmangers is unreachable for example during os updates, karma just shows the full screen error message instead of the alerts from the other alertmanager:
![image](https://github.com/prymitive/karma/assets/16702685/01ecc29b-6ff5-40e8-b938-1f180b292715)

# Setup
the problem is pretty easy to reproduce just add a second alertmanger on port where nothing is listening(9095) in my example)

CMD Flags: `-alertmanager.uri http://localhost:9093/alertmanager --alertmanager.uri http://localhost:9095/alertmanager --alertmanager.proxy --karma.name "[qa] karma " --listen.prefix /karma --alertAcknowledgement.enabled --alertAcknowledgement.duration 30m --listen.address 127.0.0.1 --config.file /etc/karma/config.yaml`

config:
```yaml
---
silences:
  comments:
    linkDetect:
      rules:
      - regex: "((CS|PIM|RCA)-[0-9]+)"
        uriTemplate: https://jira.example.com/browse/$1
labels:
  strip:
  - "@receiver"
  - pod_template_hash
  - app_kubernetes_io_version
  - app_kubernetes_io_name
  - job
  color:
    unique:
    - instance
    - pod
    - kubernetes_namespace
    - contact_group
    - clustertype
    custom:
      severity_id:
      - value: 3
        color: "#ffffff"
      - value: 4
        color: "#FFCC00"
      - value: 5
        color: "#ff4242"
      - value: 6
        color: "#a60000"
      severity:
      - value: Info
        color: "#ffffff"
      - value: Warning
        color: "#FFCC00"
      - value: Error
        color: "#ff4242"
      - value: Critical
        color: "#a60000"
      mam_stage:
      - value: dev
        color: "#3399FF"
      - value: qa
        color: "#3366CC"
      - value: prelive
        color: "#FF6600"
      - value: live
        color: "#803503"
ui:
  colorTitlebar: false
  multiGridLabel: severity
  multiGridSortReverse: true
  alertsPerGroup: 2
filters:
  default:
  - "@state!=suppressed"
```
