### ISSUE TITLE
silenceForm.strip.labels doesn't strip labels that are in the filter bar

### ISSUE THREAD

**Issue by heapdavid** [prymitive/karma#5817]
Hi, 

We have set as part of our config:

```
filters:
  default:
    - 'team!=commercial'
...
silenceForm:
  strip:
    labels:
      - team
```

So we don't see long-running alerts for our commercial team.

But every time we go to make a new silence (from the main bell on the top right, not the top of an alert) we have to remove/edit a label entry for `team`:

![image](https://github.com/prymitive/karma/assets/88432183/86925182-3837-4465-abc6-1927c0d35b50)

We'd expect this label to be stripped from the new silence form by the config.
