### ISSUE TITLE
Add Support for VictoriaMetrics API in Karma

### ISSUE THREAD

**Issue by AntonBushmelev** [prymitive/karma#6420]
Karma fails to properly handle historical queries when configured to use VictoriaMetrics as the backend instead

victoriametrics logs
```
unsupported path requested: "/api/v1/query/api/v1/labels"

```
check curl
```
curl -H "Accept: application/json" "http://172.19.0.1:9090/api/v1/query?query=ALERTS%7Balertname%3D%22MSSQLBackupTooOld%22%2Cinstance%3D%22172.17.0.1%3A9401%22%7D"
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"ALERTS","alertgroup":"mssqlexporter","alertname":"MSSQLBackupTooOld","alertstate":"firing","backup_status":"Success","backup_type":"Full","cls":"sc_1c_sql01","database_name":"Prod_ITIL","datacenter":"sc","ins":"sc_1c_sql01","instance":"172.17.0.1:9401","ip":"sc-1c-sql01.12stz.local","job":"db_mssql","metric":"backup_finish_timestamp","severity":"critical","target":"mssql_database","type":"mssql"},"value":[1750137932,"1"]},{"metric":{"__name__":"ALERTS","alertgroup":"mssqlexporter","alertname":"MSSQLBackupTooOld","alertstate":"firing","backup_status":"Success","backup_type":"Full","cls":"sc_1c_sql01","database_name":"Prod_IndSaf","datacenter":"sc","ins":"sc_1c_sql01","instance":"172.17.0.1:9401","ip":"sc-1c-sql01.12stz.local","job":"db_mssql","metric":"backup_finish_timestamp","severity":"critical","target":"mssql_database","type":"mssql"},"value":[1750137932,"1"]},{"metric":{"__name__":"ALERTS","alertgroup":"mssqlexporter","alertname":"MSSQLBackupTooOld","alertstate":"firing","backup_status":"Success","backup_type":"Full","cls":"sc_1c_sql01","database_name":"Report_KA","datacenter":"sc","ins":"sc_1c_sql01","instance":"172.17.0.1:9401","ip":"sc-1c-sql01.12stz.local","job":"db_mssql","metric":"backup_finish_timestamp","severity":"critical","target":"mssql_database","type":"mssql"},"value":[1750137932,"1"]}]},"stats":{"seriesFetched": "3","executionTimeMsec":6}}

```

cat karma.conf
```
alertmanager:
  interval: 1m
  servers:
    - cluster: "default"
      name: "main"
      uri: "http://alertmanager:9093"
      timeout: 30s
      proxy: true

history:
  enabled: true
  timeout: 30s
  workers: 3
  rewrite:
    - source: "(.*)"
      uri: "http://172.19.0.1:9090/api/v1/query"
      headers:
        Accept: "application/json"

ui:
  refresh: "30s"
  hideFiltersWhenIdle: true

labels:
  color:
    unique:
      - "alertname"
      - "instance"

filters:
  default: []

```
