### ISSUE TITLE
Unsee CSS

### ISSUE THREAD

**Issue by sylr** [prymitive/karma#667]
For those nostalgic of the unsee colors like me I made a custom css :

```css
    body {
      font-size: 1.03rem !important;
      background-color: #2c3e50 !important;
    }

    .bg-primary-transparent {
      background-color: #2c3e50 !important;
    }

    .flex-shrink-1 {
      text-align: center !important;
    }

    .components-label-name {
      color: #fff !important;
    }

    .components-label-bright .components-label-name {
      color: #000 !important;
    }

    .text-muted {
      color: #000 !important;
      font-weight: bold !important;
    }

    .card {
      border: 1px solid #e74c3c !important;
    }

    .card > .card-header.bg-light  {
      background-color: #e74c3c !important;
    }

    .card .card-header.bg-light .badge-danger {
      color: #e74c3c !important;
      background-color: #fff !important;
    }

    .card .card-header.bg-light .text-muted {
      color: #fff !important;
    }

    .card-footer {
      line-height: 1;
    }

    .components-label .components-label-name,
    .components-label .components-label-value,
    .components-label-with-hover time {
      font-size: 1.1em !important;
    }
```
