### ISSUE TITLE
Basic auth: unknown error (status 401)

### ISSUE THREAD

**Issue by r0bj** [prymitive/karma#689]
Let's test basic auth credentials:
```
curl -v -u admin:secretPassword https://alertmanager.example.com
[...]
< HTTP/2 200
```
Works fine.

karma.yaml:
```
    alertmanager:
      interval: 1m
      servers:
      - name: example
        uri: https://admin:secretPassword@alertmanager.example.com
```

karma generates error message:
```
time="2019-05-08T15:01:23Z" level=info msg="GET https://admin:xxx@alertmanager.example.com/api/v1/status timeout=10s"
time="2019-05-08T15:01:23Z" level=info msg="[example] Remote Alertmanager version: 0.17.0"
time="2019-05-08T15:01:23Z" level=error msg="[example] unknown error (status 401): {resp:0xc0006c4750} "
```

karma:v0.35
