### ISSUE TITLE
allow config test options

### ISSUE THREAD

**Issue by freeseacher** [prymitive/karma#735]
Hi! 

I'm trying to check karma config on ci before applying it to production. 
I want to check it with live version of karma to ensure syntax is ok. 
I see two approaches for that

1. launch `timeout 5 karma --config.file karma/karma.yml` and wait for something like 
```
FATA[0000] yaml: unmarshal errors:
  line 18: cannot unmarshal !!str `flase` into bool 
```
but image build on top of `gcr.io/distroless/base` that does not contain timeout and even sh 

2. add `--configtest` key to karma and exit if config is wrong 

of cause i can rebuild image by myself but that is probably not the best idea

**Comment by ekbfh** [comment]
Also need this option

**Comment by prymitive** [comment]
I can add a flag for config validation, if passed karma would just read the config in and exit with either 0 or 1.

**Comment by prymitive** [comment]
Raised #737 that adds a new flag:
```
$ LOG_CONFIG=false ./karma --check-config
INFO[0000] Version: v0.37-30-gf57e1059-dev
FATA[0000] No valid Alertmanager URIs defined
$ echo $?
1
```

**Comment by freeseacher** [comment]
Take my time to make it work. and that is fail :( 
i am using gitlab-ci and make ci task like this. 

```
check_karma:
  stage: test
  image:
    name: lmierzwa/karma:$KARMA_VERSION
    entrypoint: [""]
  before_script:
    - karma --version
  script:
    - LOG_CONFIG=false /karma --check-config --config.file karma/karma.yml
    - echo $0
  tags:
...
    - docker
```
but for some reason that job can't be done. the reason is pretty obvious. 
gitlab-runner trying to do `cd /build/dir ` but there are no cd. :(

could you please add `lmierzwa/karma:$KARMA_VERSION-alpine ` just to have sh and so on.
