### ISSUE TITLE
How can I set default label background color to gray?

### ISSUE THREAD

**Issue by liujiawinds** [prymitive/karma#800]
Btw, strip a label named `@receiver` doesn't work.

My configuration below.
![image](https://user-images.githubusercontent.com/1757754/60487715-a5309300-9cd2-11e9-94f3-e8632d8fc165.png)

Thanks in advance.

**Comment by prymitive** [comment]
> Btw, strip a label named @receiver doesn't work.

Receiver is not really a label, it's an extra field. I guess that handling of special `@foo` labels got a bit too messy.

> How can I set default label background color to gray?

The config you provided should work, I tested the following config with latest release and it works as expected:

```
    custom:
      priority:
        - value: '3'
          color: '#f8b739'
        - value: '4'
          color: '#f3dcad'
        - value: '5'
          color: '#e7eaf6'
        - value_re: .*
          color: '#666'
```

Result:
![Screenshot-20190702175312](https://user-images.githubusercontent.com/114288/60531195-4da21f80-9cf2-11e9-9da4-e35057b6280f.png)
